# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
